routes:
    default:
        url: /
        controller: App\Controller\DefaultController
        methods: [GET, POST]
        allow: [user, admin]

    index-id:
        url: /index/{id}/xd/{test}
        controller: App\Controller\IndexIdController
        methods: [GET]
        allow: []

    database:
        url: /database
        controller: App\Controller\DatabaseController
        methods: [GET, POST]
        allow: [admin]

    login:
        url: /login
        controller: App\Controller\LoginController
        methods: [POST]
        allow: [guest, user]

    register:
        url: /register
        controller: App\Controller\RegisterController
        methods: [POST]
        allow: [guest]

    promote_user_to_admin:
        url: /users/{id}/promote
        controller: App\Controller\PromoteController
        methods: [ GET ]
        allow: [ admin ]

    find_user_by_id:
        url: /users/{id}
        controller: App\Controller\UserController::findUserById
        methods: [ GET ]
        allow: [ admin ]
